"""Git worktree sandbox lifecycle for the Developer + Quality Gates retry loop - create/reset/sync/remove. Extracted from kriya/workflow/workflow.py (2026-08-11 modularization)."""

import asyncio
import difflib
import hashlib
import logging
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

logger = logging.getLogger(__name__)


def _sync_uncommitted_changes_into_worktree(repo_path: str, worktree_path: str) -> None:
    """After create_git_worktree resets the sandbox to a clean git HEAD checkout, copy
    over any uncommitted changes (modified tracked files, new untracked files) from the
    real workspace so the Developer's sandbox reflects what's actually on disk, not just
    git history. Without this, a project with any uncommitted work - the normal state of
    an in-progress feature branch - looks to the sandbox exactly like a completely fresh
    checkout of HEAD: every uncommitted file the goal expects to already exist (and any
    goal asking to "preserve"/"extend" existing work) silently vanishes from compilation,
    producing confusing "package does not exist" failures that have nothing to do with
    the actual generated code. Confirmed live: an additive goal building on a previous
    run's uncommitted output failed every retry attempt this way, with pom.xml (never
    touched by the Developer, since the goal said to leave it as-is) simply absent from
    the sandbox because it was never git-committed.

    Excludes .kriya/ (checkpoints, this very worktree) via the same pathspec already used
    for workspace-fingerprint dirty checks, and deleted-in-working-tree files are removed
    from the worktree rather than left as a stale HEAD-only copy.

    `--untracked-files=all` is required, not the default mode: a directory that is
    ENTIRELY untracked (no committed content anywhere under it) gets collapsed by git
    into one line (`?? src/`) under the default `normal` mode, rather than one line per
    file - which silently dropped the whole directory here, since the per-line copy loop
    below treats a directory entry as a no-op (`if os.path.isdir(src): continue`) and
    never recurses into it. Confirmed live: a from-scratch `src/` tree (regenerated by a
    prior run but never git-committed) never reached the worktree at all, producing a
    "package does not exist" compile failure that looked like a model mistake but was
    purely this sync gap."""
    try:
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=all", "--", ".", ":!.kriya"],
            cwd=repo_path, capture_output=True, text=True,
        )
        if status.returncode != 0 or not status.stdout.strip():
            return
        for line in status.stdout.splitlines():
            if len(line) < 4:
                continue
            code, rest = line[:2], line[3:]
            # Renames: "R  old -> new" - treat as delete-old + copy-new.
            if code.startswith("R") and " -> " in rest:
                old_rel, rest = rest.split(" -> ", 1)
                old_abs = os.path.join(worktree_path, old_rel.strip().strip('"'))
                if os.path.exists(old_abs):
                    os.remove(old_abs)
            rel = rest.strip().strip('"')
            if not rel or rel.startswith(".kriya"):
                continue
            src = os.path.join(repo_path, rel)
            dst = os.path.join(worktree_path, rel)
            if code.strip() == "D" or not os.path.exists(src):
                if os.path.exists(dst):
                    try:
                        os.remove(dst)
                    except IsADirectoryError:
                        shutil.rmtree(dst, ignore_errors=True)
                continue
            if os.path.isdir(src):
                continue
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
    except Exception as e:
        logger.warning(f"Failed to sync uncommitted changes into worktree sandbox (non-fatal, sandbox may be missing uncommitted work): {e}")


def _resolve_repo_head(repo_path: str) -> Optional[str]:
    """Resolves repo_path's actual current HEAD commit SHA. Needed because a
    worktree created with `git worktree add --detach` gets its own fixed HEAD
    pointer at creation time, not a moving ref to repo_path's branch - so
    `git checkout -f HEAD` run *inside* that worktree resolves against its own
    frozen pointer and is a no-op, never advancing to match new commits landed
    on repo_path since. Returns None if resolution fails (e.g. an empty repo
    with no commits yet), in which case callers fall back to the old "HEAD"
    behavior rather than crash."""
    try:
        res = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo_path, capture_output=True, text=True,
        )
        if res.returncode == 0:
            return res.stdout.strip()
    except Exception as e:
        logger.debug(f"Failed to resolve HEAD for '{repo_path}': {e}")
    return None


def create_git_worktree(repo_path: str) -> str:
    # 1. Quick pre-check: Is this a git repository?
    try:
        res = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=repo_path, capture_output=True, text=True)
        if res.returncode != 0:
            raise ValueError("Not a git repository")
    except Exception as e:
        raise ValueError(f"Directory is not a git repository: {e}") from e

    worktree_path = os.path.join(repo_path, ".kriya", "worktree")
    os.makedirs(os.path.dirname(worktree_path), exist_ok=True)
    
    # 2. Prune any stale/orphaned worktree records in git administrative data
    try:
        subprocess.run(["git", "worktree", "prune"], cwd=repo_path, capture_output=True)
    except Exception as e:
        logger.debug(f"git worktree prune failed (non-fatal): {e}")

    worktree_registered = False
    try:
        res = subprocess.run(["git", "worktree", "list"], cwd=repo_path, capture_output=True, text=True)
        if worktree_path in res.stdout:
            worktree_registered = True
    except Exception as e:
        logger.debug(f"git worktree list failed, assuming worktree is not registered: {e}")

    if not worktree_registered:
        if os.path.exists(worktree_path):
            shutil.rmtree(worktree_path, ignore_errors=True)
        subprocess.run(["git", "worktree", "add", "--detach", worktree_path], cwd=repo_path, check=True, capture_output=True)
    else:
        # Recreate the directory physically if it was deleted but still registered
        if not os.path.exists(worktree_path):
            try:
                subprocess.run(["git", "worktree", "prune"], cwd=repo_path, capture_output=True)
            except Exception as e:
                logger.debug(f"git worktree prune failed (non-fatal): {e}")
            subprocess.run(["git", "worktree", "add", "--detach", worktree_path], cwd=repo_path, check=True, capture_output=True)
        else:
            # Reset but preserve target/ and other build directories. "HEAD" here
            # must be resolved against repo_path, not checked out literally inside
            # the worktree - see _resolve_repo_head for why.
            target = _resolve_repo_head(repo_path)
            subprocess.run(["git", "checkout", "-f", target or "HEAD"], cwd=worktree_path, check=True, capture_output=True)
            subprocess.run(["git", "clean", "-fd"], cwd=worktree_path, check=True, capture_output=True)

    # A worktree only ever reflects git HEAD - it knows nothing about uncommitted
    # changes in the real workspace, which is the normal state of an in-progress
    # project. Copy those over now so the sandbox matches what's actually on disk.
    _sync_uncommitted_changes_into_worktree(repo_path, worktree_path)

    return worktree_path


def snapshot_untracked_files(worktree_path: str) -> Optional[set]:
    """Returns the set of currently-untracked file paths (relative to
    worktree_path) - the same `git status --porcelain --untracked-files=all`
    source _sync_uncommitted_changes_into_worktree already uses, so a
    directory that's entirely untracked is enumerated file-by-file rather
    than collapsed into one `?? dir/` line. Returns None (not an empty set)
    on any git failure, so a caller can distinguish "definitely no untracked
    files" from "couldn't tell" and skip cleanup rather than risk deleting
    something real off an unreliable read.

    Paired with clean_untracked_files_since() below - see that function's own
    docstring for the real incident this closes (Runtime Verification's
    generated-app runtime state, e.g. a JSON store, leaking across retry
    attempts inside the same reused worktree)."""
    try:
        res = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=all"],
            cwd=worktree_path, capture_output=True, text=True,
        )
        if res.returncode != 0:
            return None
    except Exception as e:
        logger.debug(f"Failed to snapshot untracked files in '{worktree_path}' (non-fatal): {e}")
        return None
    files = set()
    for line in res.stdout.splitlines():
        if line.startswith("??"):
            files.add(line[3:].strip().strip('"'))
    return files


def clean_untracked_files_since(worktree_path: str, baseline: Optional[set]) -> None:
    """Removes any file that became untracked in the worktree SINCE `baseline`
    was snapshotted (via snapshot_untracked_files, taken immediately before
    the just-finished operation) - i.e. exactly what that operation created,
    nothing that already existed beforehand.

    Added 2026-08-17 after the corpus survey's dig into `run_verification`
    found a real, previously-undiscovered mechanism bug: run_app_sequence()
    deliberately runs each verification command in the SAME worktree
    directory so state one step creates (a JSON file, a database) is visible
    to the next step WITHIN one attempt - correct and necessary for a
    goal like "add a task, then list it". But the worktree itself is reused
    across an ENTIRE run's retry attempts (create_git_worktree's own
    docstring: "so compile caches... survive between retries"), and nothing
    ever cleaned up what a PRIOR attempt's own verification run wrote to
    disk. Confirmed live (python_task_tracker, runs b-6/b-7, 2026-08-16):
    attempt 1's generated code was actually CORRECT (task added as id 1,
    marked done, correctly excluded from the final pending list) - grade()
    hallucinated a failure ("Task 1 should still be listed as completed",
    not anything the goal actually asked for), triggering a retry. From
    there, EVERY subsequent attempt's verification ran against the SAME
    tasks.json the previous attempt's run had already written to - task
    IDs kept climbing (1,2 -> ... -> 5,6 by attempt 7) and `done 1` failed
    every time because task 1 had already been consumed/renumbered by an
    earlier attempt's leftover state, producing a cascade of "the done
    command doesn't work" failures that had nothing to do with the
    generated code, which never changed in the way that mattered.

    Snapshotting immediately before run_app_sequence() and cleaning up
    immediately after (regardless of pass/fail) means every attempt's
    verification always starts from the same "freshly compiled, never run"
    baseline - compile-time build caches (target/, node_modules/, __pycache__/)
    are untouched since they already existed in `baseline` by the time this
    runs (compile always happens earlier in the same attempt), only files
    the run itself just created get removed. A None baseline (snapshot
    failed) or None/empty diff is a silent no-op, not an error - this is a
    hygiene improvement, never a gate that can itself fail the run."""
    if baseline is None:
        return
    current = snapshot_untracked_files(worktree_path)
    if current is None:
        return
    for rel in current - baseline:
        full = os.path.join(worktree_path, rel)
        try:
            if os.path.isdir(full):
                shutil.rmtree(full, ignore_errors=True)
            elif os.path.exists(full):
                os.remove(full)
        except OSError as e:
            logger.debug(f"Failed to clean up runtime artifact '{rel}' after verification run (non-fatal): {e}")


def remove_git_worktree(repo_path: str, worktree_path: str) -> None:
    """Despite the name, this resets the worktree back to repo_path's current
    commit rather than truly deleting it - the worktree is deliberately reused
    across runs so compile caches inside it (target/, node_modules/, etc.)
    survive between retries and between separate generate/fix invocations. See
    _resolve_repo_head for why "HEAD" can't be checked out literally here -
    without it, this "cleanup" was a no-op that left the worktree permanently
    frozen at whatever commit existed the first time it was ever created,
    silently hiding every commit made since from any future run that doesn't
    itself rewrite the affected files."""
    if os.path.exists(worktree_path):
        try:
            target = _resolve_repo_head(repo_path)
            subprocess.run(["git", "checkout", "-f", target or "HEAD"], cwd=worktree_path, capture_output=True)
            subprocess.run(["git", "clean", "-fd"], cwd=worktree_path, capture_output=True)
        except Exception as e:
            logger.debug(f"Failed to clean up worktree at '{worktree_path}' (non-fatal): {e}")
