#!/usr/bin/env node
/**
 * KUP v1 code generation (06 Phase B, gate A-2 P-R4). From ui/kup/schema/*.schema.json it produces, deterministically:
 *   generated/ts/*.ts        TypeScript types (json-schema-to-typescript)
 *   generated/validators.cjs precompiled Ajv validators (standalone code: no eval at runtime, so they run under the
 *                            Electron CSP `script-src 'self'`)
 *   generated/java/**.java   Java types (quicktype-core) - proves the contract is usable by a future Java host; no
 *                            Java host is built
 * `--check` regenerates into a temp dir and fails if the committed output differs (drift check for CI).
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { InputData, JSONSchemaInput, JSONSchemaStore, quicktype } from 'quicktype-core';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_DIR = join(ROOT, 'schema');
const CHECK = process.argv.includes('--check');
const OUT = CHECK ? join(ROOT, '.generated-check') : join(ROOT, 'generated');
const BASE = 'https://kriya.local/kup/v1/';

const seen = new Set(); // helper types already emitted into ts/kup.ts
const schemaFiles = readdirSync(SCHEMA_DIR).filter((f) => f.endsWith('.schema.json')).sort();
const schemas = Object.fromEntries(schemaFiles.map((f) => [f, JSON.parse(readFileSync(join(SCHEMA_DIR, f), 'utf8'))]));

/** Exported root types: [output name, schema file, JSON pointer within it]. */
const TYPES = [
  ['Envelope', 'common.schema.json', '#/$defs/Envelope'],
  ['KupError', 'common.schema.json', '#/$defs/KupError'],
  ['Section', 'common.schema.json', '#/$defs/Section'],
  ['Capabilities', 'capabilities.schema.json', '#'],
  ['HistoryList', 'history.schema.json', '#/$defs/HistoryList'],
  ['RunSummary', 'history.schema.json', '#/$defs/RunSummary'],
  ['RunDetail', 'history.schema.json', '#/$defs/RunDetail'],
  ['RunEvent', 'history.schema.json', '#/$defs/RunEvent'],
  ['ContextRecord', 'history.schema.json', '#/$defs/ContextRecord'],
  ['AttributionRecord', 'history.schema.json', '#/$defs/AttributionRecord'],
  ['Comparison', 'history.schema.json', '#/$defs/Comparison'],
  ['Prompt', 'history.schema.json', '#/$defs/Prompt'],
  ['WorkspaceStatus', 'workspace.schema.json', '#'],
  ['Consistency', 'common.schema.json', '#/$defs/Consistency'],
  ['SnapshotSummary', 'snapshot.schema.json', '#/$defs/SnapshotSummary'],
  ['SnapshotAcquireResult', 'snapshot.schema.json', '#/$defs/SnapshotAcquireResult'],
  ['SnapshotList', 'snapshot.schema.json', '#/$defs/SnapshotList'],
  ['SnapshotPrune', 'snapshot.schema.json', '#/$defs/SnapshotPrune'],
  ['KupRequest', 'host-contract.schema.json', '#/$defs/KupRequest'],
  ['OpenInIdeRequest', 'host-contract.schema.json', '#/$defs/OpenInIdeRequest'],
  ['OpenInIdeResult', 'host-contract.schema.json', '#/$defs/OpenInIdeResult'],
  ['HostInfo', 'host-contract.schema.json', '#/$defs/HostInfo'],
  ['HostMessages', 'host-contract.schema.json', '#/$defs/Messages'],
];

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, 'ts'), { recursive: true });
mkdirSync(join(OUT, 'java', 'kup'), { recursive: true });

// ---- TypeScript ----------------------------------------------------------------------------------------------
let tsOut = `/* GENERATED by ui/kup/scripts/generate.mjs from ui/kup/schema - do not edit. KUP v1. */\n/* eslint-disable */\n`;
for (const [name, file, pointer] of TYPES) {
  const schema = pointer === '#' ? schemas[file] : { ...resolvePointer(schemas[file], pointer), $id: undefined };
  const rooted = { ...schema, title: name, $id: undefined, $schema: 'http://json-schema.org/draft-07/schema#' };
  // Inline $defs of the owning file so local refs resolve; external refs resolve through cwd.
  if (schemas[file].$defs && pointer !== '#') rooted.$defs = schemas[file].$defs;
  const ts = await compile(rooted, name, { cwd: SCHEMA_DIR, bannerComment: '', additionalProperties: true, declareExternallyReferenced: true, style: { singleQuote: true, printWidth: 120 }, unknownAny: true });
  tsOut += `\n// ---- ${name} (${file}${pointer}) ----\n${dedupeHelpers(ts)}`;
}
writeFileSync(join(OUT, 'ts', 'kup.ts'), tsOut);

// ---- Ajv standalone validators ----------------------------------------------------------------------------------
const ajv = new Ajv({ code: { source: true, esm: true }, allErrors: true, strict: true, allowUnionTypes: true });
for (const [file, schema] of Object.entries(schemas)) ajv.addSchema(schema, BASE + file);
const validatorNames = Object.fromEntries(TYPES.map(([name, file, pointer]) => [`validate${name}`, BASE + file + (pointer === '#' ? '' : pointer)]));
let code = standaloneCode(ajv, validatorNames);
// The only runtime helper Ajv needs for these schemas is ucs2length (string length in code points, for
// minLength/maxLength). Inline it so the generated module has NO dependency (ui/shared's allowlist, P-R1).
const UCS2 = `function ucs2length(str) { const len = str.length; let length = 0, pos = 0, value; while (pos < len) { length++; value = str.charCodeAt(pos++); if (value >= 0xd800 && value <= 0xdbff && pos < len) { value = str.charCodeAt(pos); if ((value & 0xfc00) === 0xdc00) pos++; } } return length; }`;
code = code.replace(/const\s+func(\d+)\s*=\s*require\("ajv\/dist\/runtime\/ucs2length"\)\.default;?/g, (_m, n) => `const func${n} = ${UCS2};`);
if (/require\(/.test(code)) throw new Error('validators still require() a runtime helper: ' + (code.match(/require\([^)]*\)/g) ?? []).join(', '));
writeFileSync(join(OUT, 'validators.d.mts'), `/* GENERATED: declarations for validators.mjs. */\n${Object.keys(validatorNames).map((n) => `export const ${n}: ((value: unknown) => boolean) & { errors?: { instancePath: string; message?: string; params?: Record<string, unknown> }[] | null };`).join('\n')}\n`);
writeFileSync(join(OUT, 'validators.mjs'), `/* GENERATED by ui/kup/scripts/generate.mjs - precompiled Ajv validators (no eval, no dependency). */\n/* eslint-disable */\n${code}`);

// ---- Java (quicktype) -----------------------------------------------------------------------------------------
class LocalStore extends JSONSchemaStore {
  async fetch(address) {
    const file = address.replace(BASE, '').split('#')[0];
    return schemas[file] ? JSON.parse(JSON.stringify(schemas[file])) : undefined;
  }
}
const input = new JSONSchemaInput(new LocalStore());
for (const [name, file, pointer] of TYPES) {
  if (name === 'HostMessages') continue; // a documentation object, not a wire type
  const uri = BASE + file + (pointer === '#' ? '' : pointer);
  await input.addSource({ name, uris: [uri] });
}
const inputData = new InputData();
inputData.addInput(input);
const java = await quicktype({ inputData, lang: 'java', rendererOptions: { package: 'kup', 'array-type': 'list', 'just-types': 'false', 'acronym-style': 'original', 'datetime-provider': 'java8' } });
for (const { filename, lines } of java.results ? [] : []) void filename;
// quicktype returns one SerializedRenderResult; split by the `// Foo.java` markers it emits for Java.
const text = java.lines.join('\n');
const parts = text.split(/^\/\/ ([A-Za-z0-9_]+\.java)\n/m);
const files = {};
for (let i = 1; i < parts.length; i += 2) files[parts[i]] = parts[i + 1];
if (!Object.keys(files).length) files['Kup.java'] = text;
// Unknown-field preservation (P-24): quicktype's Java classes drop unknown properties, so every class generated from
// an OPEN schema object gets a Jackson any-getter/any-setter map. Classes from the strict host contract
// (additionalProperties: false) keep refusing unknown fields, exactly like the TypeScript host validators.
const STRICT_JAVA_CLASSES = new Set(['OpenInIdeRequest', 'OpenInIdeResult', 'HostInfo', 'KupRequest']);
const ANY_PROPS = `
    // Added by generate.mjs: unknown properties are preserved verbatim (P-24).
    private final java.util.Map<String, Object> additionalProperties = new java.util.LinkedHashMap<>();
    @JsonAnyGetter
    public java.util.Map<String, Object> getAdditionalProperties() { return additionalProperties; }
    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) { additionalProperties.put(name, value); }
`;
for (const [name, body] of Object.entries(files)) {
  const cls = name.replace(/\.java$/, '');
  let out = body.trimEnd();
  if (!STRICT_JAVA_CLASSES.has(cls) && /^public class /m.test(out) && !/^public enum /m.test(out)) {
    out = out.replace(/^(public class [A-Za-z0-9_]+ \{)/m, `$1${ANY_PROPS}`);
    if (!/import com\.fasterxml\.jackson\.annotation\.\*;/.test(out)) out = out.replace(/^(package kup;\n)/m, '$1\nimport com.fasterxml.jackson.annotation.JsonAnyGetter;\nimport com.fasterxml.jackson.annotation.JsonAnySetter;');
  } else if (STRICT_JAVA_CLASSES.has(cls) && /^public class /m.test(out)) {
    out = out.replace(/^(public class )/m, '@JsonIgnoreProperties(ignoreUnknown = false)\n$1');
    if (!/import com\.fasterxml\.jackson\.annotation\.\*;/.test(out)) out = out.replace(/^(package kup;\n)/m, '$1\nimport com.fasterxml.jackson.annotation.JsonIgnoreProperties;');
  }
  writeFileSync(join(OUT, 'java', 'kup', name), `// GENERATED by ui/kup/scripts/generate.mjs from ui/kup/schema - do not edit.\n${out}\n`);
}

// ---- check mode --------------------------------------------------------------------------------------------------
if (CHECK) {
  const committed = join(ROOT, 'generated');
  const diffs = [];
  const walk = (dir, base = dir) => readdirSync(dir).flatMap((n) => { const p = join(dir, n); return statSync(p).isDirectory() ? walk(p, base) : [relative(base, p)]; });
  const a = new Set(walk(OUT)), b = new Set(existsSync(committed) ? walk(committed) : []);
  for (const f of [...a, ...b]) {
    if (!a.has(f) || !b.has(f)) { diffs.push(`${f}: ${a.has(f) ? 'missing from generated/' : 'stale in generated/'}`); continue; }
    if (readFileSync(join(OUT, f), 'utf8') !== readFileSync(join(committed, f), 'utf8')) diffs.push(`${f}: differs`);
  }
  rmSync(OUT, { recursive: true, force: true });
  if (diffs.length) { console.error('generated output is stale - run `npm run generate -w @kriya-ui/kup`:\n - ' + diffs.join('\n - ')); process.exit(1); }
  console.log(`generated output is current (${a.size} files)`);
} else {
  console.log(`generated: ts/kup.ts (${TYPES.length} types), validators.mjs (${Object.keys(validatorNames).length} validators), java/kup/*.java (${Object.keys(files).length} files)`);
}

function resolvePointer(doc, pointer) {
  return pointer.replace(/^#\/?/, '').split('/').filter(Boolean).reduce((o, k) => o[k], doc);
}
/** json-schema-to-typescript re-emits externally referenced helper types per call; keep the first definition only. */
function dedupeHelpers(ts) {
  return ts.split(/\n(?=export (?:interface|type) )/).filter((block) => {
    const m = block.match(/^export (?:interface|type) ([A-Za-z0-9_]+)/);
    if (!m) return true;
    if (seen.has(m[1])) return false;
    seen.add(m[1]);
    return true;
  }).join('\n');
}
